site_name: KnowledgeBase
site_url: https://kb.harshjain.dev/
site_dir: "build/"
edit_uri: ""
copyright: "© Harsh Jain"
site_author: "Harsh Jain"
site_description: "My knowledgebase"


theme:
  name: material
  custom_dir: material
  language: "en"
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: pink
      accent: pink 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

  


# Repo Details
repo_url: "https://github.com/hrkj-18/kb.harshjain.dev"
repo_name: hrkj-18/kb.harshjain.dev

plugins:
  - search:
      lang: en

# Extra Configuration for Material Theme

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/hrkj-18"
      name: Harsh Jain on Github
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/hrkj-18"
      name: Harsh Jain on Twitter
    - icon: fontawesome/brands/linkedin
      link: "https://linkedin.com/in/hrkj-18"
      name: Harsh Jain on Linkedin
    - icon: fontawesome/brands/facebook
      link: "https://facebook.com/hrkj-18"
      name: Harsh Jain on Facebook
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/hrkj-18"
      name: Harsh Jain on Instagram
    # - icon: fontawesome/brands/terminal
    #   link: "https://harshjain.dev"
    #   name: Harsh Jain
  feature:
    tabs: true

#  analytics:
#   provider: google
#   property: UA-XXXXXXXX-X

# Page tree
nav:
  - Home: index.md
  - Python:
    - Introduction to Python:
      - Python Basics: python/introduction-to-python/python-basics/index.md
      - Python Lists: python/introduction-to-python/python-lists/index.md
      - Functions and Packages: python/introduction-to-python/functions-and-packages/index.md
      - Numpy: python/introduction-to-python/numpy/index.md
  - Pandas:
    - Chapter 1: pandas/chapter-1.md
    - Chapter 2: pandas/chapter-2.md  
  - Chatbots:
    - Chatbots 101: chatbots/chatbots101.md
  - Statistics:
    - Index: statistics/index.md
  - Spreadsheets:
    - Basics: spreadsheets/basics.md
    - Formulas Part 1: spreadsheets/formulas-1.md
    - Formulas Part 2: spreadsheets/formulas-2.md
    - Formulas Part 3: spreadsheets/formulas-3.md
    - Errors: spreadsheets/errors.md
